name: Update Contributors
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  add-contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add contributor
        uses: all-contributors/add-contributors@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}